### ISSUE TITLE
Przycisk refresh na task board

### ISSUE THREAD

**Issue by miccze007** [babaczyk/TIM#14]
Gdy ktoś przypisze mi nowe zadanie, bądź utworze je z Outlooka przycisk refresh nic nie zmienia. Muszę przejść na stronę gł , przejść na task board dopiero wtedy te zadanie jest widoczne

**Comment by babaczyk** [comment]
Duplika, czeka na rozwiązanie :) 
[DUPLIKAT](https://github.com/babaczyk/TIM/issues/10)
