### ISSUE TITLE
Dodawanie zadań z Outlooka

### ISSUE THREAD

**Issue by miccze007** [babaczyk/TIM#5]
Nie działa dodawanie zadań z Outlooka, komunikat odnośnie uprawnień.

"You do not have the following permissions on TableData Office Add-in: Delete"

**Comment by babaczyk** [comment]
Rozwiązane

**Comment by miccze007** [comment]
Kolejny komunikat podczas dodawania zadania (w załączniku).

![taskboard](https://user-images.githubusercontent.com/59958309/76193940-64840480-61e5-11ea-80c8-248cd741a4c1.png)

**Comment by babaczyk** [comment]
Scenariusz - co po kolei klikasz poproszę.
