### ISSUE TITLE
Brak uprawnień do tablicy zadań (Około 8:10 jeszcze działało )

### ISSUE THREAD

**Issue by mikeazurek** [babaczyk/TIM#6]
Brak uprawnień do tablicy zadań (Około 8:10 jeszcze działało )
![login](https://user-images.githubusercontent.com/58667581/76191966-dd349200-61e0-11ea-9f97-fd53323d9475.png)

![err1](https://user-images.githubusercontent.com/58667581/76191958-dad23800-61e0-11ea-8aa7-27ab5b12eb3b.png)

![err2](https://user-images.githubusercontent.com/58667581/76191960-dc9bfb80-61e0-11ea-99bd-4ae82e9affd3.png)

![err3](https://user-images.githubusercontent.com/58667581/76191964-dd349200-61e0-11ea-9c70-1b27e04c4fb7.png)

**Comment by babaczyk** [comment]
To samo co zgłoszenie poprzednie - rozwiązane już
