### ISSUE TITLE
Nie znikający przycisk stop

### ISSUE THREAD

**Issue by miccze007** [babaczyk/TIM#7]
Gdy zakańczamy zadanie z poziomu listy, samo zadania zatrzymuje się, natomiast sam pasek/przycisk nie znika, należy użyć funkcji Refresh. W załączniku screen 

![taskboard](https://user-images.githubusercontent.com/59958309/76193384-24705200-61e4-11ea-9c31-1eabb1165edf.png)

**Comment by babaczyk** [comment]
Rozwiązane.
